services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.prod
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    depends_on:
      mongo:
        condition: service_healthy
