name: Main Branch Pipeline

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Backend
      - name: Backend test & build
        run: |
          cd backend
          npm ci
          npm test

      # Frontend
      - name: Frontend test & build
        run: |
          cd frontend
          npm ci
          npm run lint
          npm run test
          npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-doc-backend ./backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-doc-backend

      - name: Build and push frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/hello-doc-frontend ./frontend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/hello-doc-frontend
