name: Pull Request Checks

on:
  pull_request:
    branches: [develop, main]

jobs:
  pr-check:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand({ ping: 1 })'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      MONGODB_URI: ${{vars.MONGODB_URI_TEST}}
      JWT_SECRET: ${{ secrets.JWT_SECRET_TEST }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install backend dependencies
        run: |
          cd backend
          npm ci

      - name: Run backend tests
        run: npm test
        working-directory: backend

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm ci

      - name: Lint frontend
        run: npm run lint
        working-directory: frontend

      - name: Run frontend tests
        run: npm run test
        working-directory: frontend

      - name: Build frontend
        run: npm run build
        working-directory: frontend

